### PR TITLE
fix: usage with tokio panics

### PR DESCRIPTION
**Pull request by adnanjpg**
fixes https://github.com/makarski/gauth-rs/issues/25

### CODE REVIEW

**Comment by adnanjpg** [comment]
at this stage all the tests are disabled. as most of the functions are now async, we're required to have an async test library. tokio::test would probably do the trick, should I go ahead and implement tokio::test? @makarski

**Comment by adnanjpg** [comment]
I've just converted the tests that require async from `#[test]` to `#[tokio::test]`

**Comment by makarski** [comment]
Thank you @adnanjpg! at the first glance this looks good 👍 I will have a more closer look in the afternoon so that we can go over feedback if any and get the change in.

**Review by makarski — APPROVED** [review]

**Comment by makarski** [comment]
Thank you for the PR, looks good to merge. It would be great also to update the README file code snippets.

**Comment by adnanjpg** [comment]
sure, but should I just go ahead and make all the examples in the README use `tokio`?

like:
```
#[tokio::main]
async fn main() {
    gauth::serv_account::ServiceAccount::from_file(
        "service-account-key.json",
        vec!["https://www.googleapis.com/auth/firebase.messaging"],
    );
}
```

**Comment by makarski** [comment]
That'd be great

**Comment by adnanjpg** [comment]
@makarski please check the updated README

**Review by makarski — APPROVED** [review]

**Comment by makarski** [comment]
@adnanjpg just publish v0.6 with your changes https://crates.io/crates/gauth/0.6.0 - many thanks! 🚀

**Comment by adnanjpg** [comment]
@makarski thanks to you for maintaining this amazing package 🙏

**Pull request merged**
